export const AUTH_LOGGING_IN = '[AUTH] LOGGING_IN';
export const AUTH_NOT_LOGGING_IN = '[AUTH] AUTH_NOT_LOGGING_IN';
export const AUTH_RESET_STATE = '[AUTH] AUTH_RESET_STATE';
export const AUTH_LOGGED_IN = '[AUTH] LOGGED_IN';
export const AUTH_ERR_LOG_IN = '[AUTH] ERR_LOG_IN';
export const AUTH_LOGOUT = '[AUTH] LOGOUT';
export const AUTH_CLEAR_LOGIN_ERROR_MESSAGE = '[AUTH] CLEAR_LOGIN_ERROR_MESSAGE';
