export const SET_ERRORS = '[ERRORS] SET_ERRORS';
export const RESET_ALL_ERRORS = '[ERRORS] RESET_ALL_ERRORS';
export const RESET_ERRORS = '[ERRORS] RESET_ERRORS';
export const RESET_ERRORS_EXCEPT = '[ERRORS] RESET_ERRORS_EXCEPT';
