export const REQUESTS_IN_PROGRESS_LOAD_PROFILE = '[PROFILE] REQUESTS_IN_PROGRESS_LOAD_PROFILE';
export const REQUESTS_IN_PROGRESS_LOADED_PROFILE = '[PROFILE] REQUESTS_IN_PROGRESS_LOADED_PROFILE';
export const LOADED_PROFILE = '[PROFILE] LOADED_PROFILE';
export const UPDATED_PROFILE = '[PROFILE] UPDATED_PROFILE';
export const REQUESTS_IN_PROGRESS_UPDATE_PROFILE = '[PROFILE] REQUESTS_IN_PROGRESS_UPDATE_PROFILE';
export const REQUESTS_IN_PROGRESS_UPDATED_PROFILE = '[PROFILE] REQUESTS_IN_PROGRESS_UPDATED_PROFILE';
