export const REQUESTS_IN_PROGRESS_REGISTER = '[SIGN-UP] REQUESTS_IN_PROGRESS_REGISTER';
export const REGISTERED_OK = '[SIGN-UP] REGISTERED_OK';
export const REGISTERED = '[SIGN-UP] REGISTERED';
export const RESET_REGISTRATION = '[SIGN-UP] RESET_REGISTRATION';
